### ISSUE TITLE
Renaming the library

### ISSUE THREAD

**Issue by areller** [areller/RedSharper#1]
There has been some justified criticism about the name of the library
https://www.reddit.com/r/csharp/comments/cpji2i/redsharper_a_library_for_executing_c_on_redis/

Need suggestions for new names

**Comment by areller** [comment]
RedSharp (by u/decPL)

**Comment by areller** [comment]
FluentRedis (by u/BusinessBro7)

**Comment by areller** [comment]
RediC# (by u/readmond)

**Comment by areller** [comment]
RedSharper (keeping the name)

**Comment by arikle** [comment]
RediSharp

**Comment by areller** [comment]
RediSharp
